// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.google.com/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath 'com.google.gms:google-services:4.4.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.6'
        classpath 'com.google.android.gms:oss-licenses-plugin:0.10.10'
    }
}

// Manual version (for CI compatibility)
ext {
    // Gunakan timestamp untuk version code
    version_code = (System.currentTimeMillis() / 1000).toInteger()
    // Version name manual
    version_name = "1.0.0"
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com/' }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}